name: taper_toolkit_app
description: "The Taper Toolkit — your guided path to a steady and clear recovery."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.5
  table_calendar: ^3.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  fl_chart: ^0.69.0
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
