// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gclO2HZOQFAleoFrkFg5hPMTXt_Xriw',
    appId: '1:524186089260:android:496b6c2755f28ee12f1e89',
    messagingSenderId: '524186089260',
    projectId: 'tapertoolkit',
    storageBucket: 'tapertoolkit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDciwxjnhSp3Xdx3tOYeuNGJlGQwLJhoqM',
    appId: '1:524186089260:ios:c26fcefc73bb03312f1e89',
    messagingSenderId: '524186089260',
    projectId: 'tapertoolkit',
    storageBucket: 'tapertoolkit.firebasestorage.app',
    iosBundleId: 'com.millsbrands.taperToolkitApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-TVC3w4jWpV_KKMrxTXKBvANlJQgKeRo',
    appId: '1:524186089260:web:a171ea55fc9169022f1e89',
    messagingSenderId: '524186089260',
    projectId: 'tapertoolkit',
    authDomain: 'tapertoolkit.firebaseapp.com',
    storageBucket: 'tapertoolkit.firebasestorage.app',
    measurementId: 'G-8PZWZLK9TR',
  );

}